### ISSUE TITLE
Implement all function from SublimeText SFTP package

### ISSUE THREAD

**Issue by yongkangchen** [yongkangchen/remote-sync#39]
Implement all function from SublimeText SFTP package.
# TODO
- [x] Upload
- [x] Download
- [x] Diff
- [x] Edit Remote Mapping...
- [x] Delete Remote
- [ ] Rename Local and Remote
- [ ] Delete Local and Remote
- [ ] Sync Local -> Remote...
- [ ] Sync Remote -> Local...
- [ ] Sync Both Directions...
- [ ] Bowser Remote...
- [ ] Add Alternate Remote Mapping...
- [ ] Switch Remote Mapping...
- [ ] Map to Remote...
- [ ] confirm_overwrite_newer

**Comment by jakesym** [comment]
Would "sync down on open" be possible too?

**Comment by udokmeci** [comment]
Another plus for st sftp is keeping alive the connection which gives very fast uploading time, almost 10 times faster.

I guess it works with child processes but not sure if may work on, but definitely it is missing.

**Comment by AdrienCS** [comment]
+1 for  Delete Local and Remote
